### ISSUE TITLE
Negative parameters cannot be encoded

### ISSUE THREAD

**Issue by moriaab** [paritytech/ethabi#111]
I am using ethabi library and I don't succeed to encode negative parameters for "int" Solidity type. Is there a way to do this? Thank you.

**Comment by nanexcool** [comment]
Bump! Can't find a way to do this either

**Comment by dvdplm** [comment]
@moriaab is [this](https://github.com/paritytech/ethabi/blob/a9b588df4db93c0151d0180f041a588354b583ca/cli/src/main.rs#L269) a valid test for what you are trying to do? Any other use cases we should be aware of?
