### ISSUE TITLE
fix 6.0.0 interface

### ISSUE THREAD

**Issue by debris** [paritytech/ethabi#119]
from https://github.com/paritytech/ethabi/pull/85#issuecomment-416182395

> as I was trying to update parity to version `6.0.0` I've noticed that this pull request is fundamentally broken. In particular, `ContractFunction` trait. It's not possible to decode function output without encoding it first! I'm going to revert this part of the pull request

**Comment by debris** [comment]
the summary of the discussion with @tomusdrw 

I would like the interface to look as follows:

```rust
// basic encoding
let encoded  = contract_name::function_name::encode_input(param_1, param_2, param_n);

// basic decoding
let decoded = contract_name::function_name::decode_output(output);

// encode call && create decoder
let (encoded, decoder) = contract_name::function_name::call(param_1, param_2, param_n);
// execute the contract here and get the output
let output = { unimplemented!() };
let decoded = decoder.decode(output);

// where decoder is a structure that implements
trait Decoder {
  type Output;
  fn decode(bytes: &[u8]) -> Self::Output;
}
```

I don't think we need anything else in a public interface

**Comment by tomusdrw** [comment]
I like the idea, although would extend it a bit for two structs:
```rust
struct contract_name::function_name::Encoder;
struct contract_name::function_name::Decoder;

// where

impl Decoder for contract_name::function_name::Decoder {
 type Output = ...;
}

impl Encoder for contract_name::function_name::Encoder {
  type Params = (param_1, param_2, param_3);
  fn encode(params: Self::Params) -> Vec<u8> { ... }
}
```


Exposing this two structs (implementing corresponding `Encoder` and `Decoder` interfaces) would allow you to write fully generic code both for inputs and outputs.
