### ISSUE TITLE
Conflicting LICENSE

### ISSUE THREAD

**Issue by sorccu** [paritytech/ethabi#131]
All `Cargo.toml` files in this repo (for example, [ethabi's Cargo.toml](https://github.com/paritytech/ethabi/blob/7f822e827cf8b5acd9b585b7ea3a5965f46546d4/ethabi/Cargo.toml#L6)) claim that their respective crates are MIT licensed, and it's also the license displayed at https://crates.io. However, the actual [LICENSE](https://github.com/paritytech/ethabi/blob/7f822e827cf8b5acd9b585b7ea3a5965f46546d4/LICENSE), only visible if you take the extra step to visit the repo, is GPL V3.0.

Is GPL V3.0 the intended license?

**Comment by debris** [comment]
great catch! I believe that the LICENSE file was missing and was added automatically. Personally, I see no reason for this repo to be under GLP V3.0. @5chdn @kirushik do you mind if I change the LICENSE file to MIT?

**Comment by 5chdn** [comment]
We use only GPLv3 or APLv2 across our repositories. If this tool is meant to less strict licensed, we should publish it under APLv2 which is pretty similar to MIT.

**Comment by debris** [comment]
This tool is developed since mid 2016. Do you know if we need all contributors to agree to change it to APLv2?

**Comment by 5chdn** [comment]
We have a CLA bot, don't we? :man_facepalming:

**Comment by debris** [comment]
Not for this repo, cause (as a tool) it was intended to be MIT 😅 I added the license to `Cargo.toml`, but forgot to add a LICENSE file.

But if we assume that all contributions were made as MIT (not GPL), I believe we can do whatever we want.

**Comment by 5chdn** [comment]
I only see two external contributors. Yeah, go ahead.
