### ISSUE TITLE
Fields `events` of struct `Contract` returns vector of events

### ISSUE THREAD

**Issue by fubuloubu** [paritytech/ethabi#154]
I'm not sure why this is, but the `events` HashMap field in the `Contract` struct [here](https://docs.rs/ethabi/8.0.0/ethabi/struct.Contract.html#structfield.events) returns a vector of events from the Hashmap, instead of just a singular event. This is kind of annoying to work with, and it's not immediately obvious why this is even the case in any of the docs or code comments.

**Comment by dvdplm** [comment]
I've read https://solidity.readthedocs.io/en/v0.5.3/abi-spec.html#events now a couple of times and I am having a hard time deciding on what the right behaviour here is.
/cc @tomusdrw @debris or maybe @Jannis

**Comment by tomusdrw** [comment]
Since afaik Solidity allows you to have multiple events with the same name and different signature, we store all of them here.

For convenience if you expect only one event you can use this getter:
https://docs.rs/ethabi/8.0.0/ethabi/struct.Contract.html#method.event

**Comment by Jannis** [comment]
Yes, that's the reason. Same with functions. Both can be overloaded with different signatures and just storing one of them drops important information from the ABI.

**Comment by Jannis** [comment]
It may be worth making there events and functions fields private, because they are an implementation detail. The getter and iterator functions should suffice.
