### ISSUE TITLE
encoding many arguments runs out of memory!

### ISSUE THREAD

**Issue by MrChico** [paritytech/ethabi#161]
```sh
export V=[{"constant":false,"gas":null,"inputs":[{"type":"address","name":""},{"type":"address","name":""},{"type":"uint256","name":""},{"type":"uint256","name":""},{"type":"uint256","name":""},{"type":"uint256","name":""},{"type":"address","name":""},{"type":"uint8","name":""},{"type":"bytes32","name":""},{"type":"bytes32","name":""},{"type":"address","name":""},{"type":"address","name":""},{"type":"uint256","name":""},{"type":"uint256","name":""},{"type":"bool","name":""},{"type":"uint8","name":""},{"type":"bytes32","name":""},{"type":"bytes32","name":""}],"name":"lotsofstuff","outputs":[],"payable":false,"stateMutability":null,"type":"function"}]
ethabi encode function <(echo $V) lotsofstuff -p 2C33B04ae6B405dEE94a6503dbe6a7CaD3f082Ca -p 2C33B04ae6B405dEE94a6503dbe6a7CaD3f082Ca -p 0000000000000000000000000000000000000000000000001bc16d674ec80000 -p 00000000000000000000000000000000000000000000000001671455cef6f770 -p 0000000000000000000000000000000000000000000000000000000000000000 -p 0000000000000000000000000000000000000000000000000000000000000000 -p c3455912Cf4bF115835A655c70bCeFC9cF4568eB -p 28 -p 7b93f2490c1833e65f9bfa58cd50e9f097edc408e65ebe88a5551dfb53ec3755 -p 4ab85d434db4881066e773411c6cf6b86966f4b5860f475b4dba2fa5608302ce -p 2C33B04ae6B405dEE94a6503dbe6a7CaD3f082Ca -p 2ef865ca017912c872826e25736a7a11f94235af -p 0000000000000000000000000000000000000000000000000000000000000000 -p 0000000000000000000000000000000000000000000000000000000000000000 -p 1 -p 28 -p 020303e12cbea2da5ab221a728bac53b8618cf8d9f3f4968cd24a7d9d1cf6abe -p 1e5a551d56422020a5b8f9b70d19b3771b0fc4c79334e353cef42a8eeeecc879 -l
```

For me running such a process on mac it is forcibly killed after ~2 minutes after eating up too much memory. (I thought rust was supposed to not do this :( ) what's going on here?

**Comment by MrChico** [comment]
Can confirm that this nukes my nix machine as well

**Comment by dvdplm** [comment]
@cecton one for you perhaps?

**Comment by cecton** [comment]
> I thought rust was supposed to not do this :( 

In the end Rust compiles exactly what you asked. If the sole purpose of a program would be to fill the memory, Rust will not prevent it. But I will investigate to see what's going on.

**Comment by cecton** [comment]
It's probably a bug in docopt. It tries to deserialize the command line arguments but somehow it never gets back to the CLI. Will do more investigation.

**Comment by cecton** [comment]
I managed to reproduce it: https://github.com/cecton/docopt.rs/tree/infinite-loop-filling-memory

Now to fix it...... that's a different story

**Comment by dvdplm** [comment]
Do we have an issue open with docopt?

**Comment by cecton** [comment]
@dvdplm I have not created one yet. I was hoping to fix the problem easily but it doesn't go well so I give up for today.

All I can say is:
1. I made a test case on this fork: https://github.com/cecton/docopt.rs/tree/infinite-loop-filling-memory that reproduce the issue
2. If I delete enough arguments (5x or 6x `-p ...`), the parser actually work! But it takes >2.6GB of memory and a huge amount of time but it works.

As plan of action I see only 2 way to solve this:
1. We do fix the issue in docopt
2. We refactor the code and switch to structopt at the same time

I'm not a big fan of giving up on this but the author said in the readme:

> This crate is unlikely to see significant future evolution. The primary reason to choose this crate for a new project is if you're specifically interested in using docopt syntax for your project. However, the wider docopt project is mostly unmaintained at this point.
> 
> Consider using clap or possibly structopt instead.

I don't mind debugging it but I have the feeling we just won't have that issue with structopt.

**Comment by cecton** [comment]
@dvdplm well at least that solves the question of keeping docopt or not.
