### ISSUE TITLE
Fix lenient parsing of negative integers.

### ISSUE THREAD

**Issue by debris** [paritytech/ethabi#2]
Basically make [this test](https://github.com/ethcore/ethabi/blob/master/src/bin/main.rs#L217-L224) work.

**Comment by tjayrush** [comment]
If you change this line: https://github.com/ethcore/ethabi/blob/master/src/bin/main.rs#L221 which reads:

```
let command = "ethabi encode paramas -v int256 -2 --lenient".split(" ");
```

to this:

```
let command = "ethabi encode params --lenient -v int256 -- -2".split(" ");
```

There were two errors. (1) the word 'params' was misspelled, and (2) the '--' is docent's way of saying "everything that follows is from the shell and should not be interpreted as a -dash option.  This doesn't fix the problem with docopt (which seems to have trouble accepting negative numbers), but it does make the test pass. You have to remove the #[ignore] line as well. 

I would make a pull request, but I'm not sure how to do that. If you instruct me, I would be happy to, or I guess you can just fix it yourself.

**Comment by dvdplm** [comment]
Closed by https://github.com/paritytech/ethabi/pull/173
