### ISSUE TITLE
cargo install ethabi-cli

### ISSUE THREAD

**Issue by nisang** [paritytech/ethabi#39]
ubuntu install ethab-eth is failed/
logs:
error: struct field shorthands are unstable (see issue #37340)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ethabi-2.0.0/src/contract.rs:41:13
   |
41 |             constructor,
   |             ^^^^^^^^^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ethabi-2.0.0/src/contract.rs:42:13
   |
42 |             events,
   |             ^^^^^^

error: struct field shorthands are unstable (see issue #37340)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ethabi-2.0.0/src/contract.rs:43:13
   |
43 |             functions,
   |             ^^^^^^^^^

error: aborting due to 3 previous errors

error: failed to compile `ethabi-cli v2.0.1`, intermediate artifacts can be found at `/tmp/cargo-install.LdT7tF0eMvCF`

Caused by:
  Could not compile `ethabi`.

how to continue....compile

**Comment by rphmeier** [comment]
@nisang please update `rustc` to latest 1.18.0
