### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by rstormsf** [paritytech/ethabi#40]
`ethabi encode params -v uint256 200000000000000000000 -v uint256 200000000000000000 -v uint256 2713998 -v 2813898`
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `4`, right: `3`)', /Users/rstorm/.cargo/registry/src/github.com-1ecc6299db9ec823/ethabi-cli-2.0.1/src/main.rs:135
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by dvdplm** [comment]
`docopt` is replaced by `structopt` as of #164
