### ISSUE TITLE
ethabi_derive into for vectors should be generated differently

### ISSUE THREAD

**Issue by debris** [paritytech/ethabi#45]
currently it is:

```rust
fn foo<T0: Into<Uint>, T1: Into<Vec<Address>>>(
    &self, 
    n: T0, 
    a: T1
) -> Bytes
```

instead it should be:

```rust
fn foo<T0: Into<Uint>, T1: Into<Address>>(
    &self, 
    n: T0, 
    a: Vec<T1>
) -> Bytes
```

@tomusdrw do you agree❓

**Comment by tomusdrw** [comment]
Makes sense, although maybe it should be `&[T1]` instead of `Vec<T1>`?

**Comment by debris** [comment]
if we do `&[T1]` we won't be able to call `Into`, cause it's moving the value

**Comment by rphmeier** [comment]
Should rather be `T1: IntoIterator<Item=U>`
