### ISSUE TITLE
ethabi Error "InvalidName" on Valid Name

### ISSUE THREAD

**Issue by Kmoneal** [paritytech/ethabi#75]
Using web3 version 0.1.0 and ethabi verion 4.0.0/4.2.0. 

Traced back error message form rust-web3 to ethabi (received the same result from ethabi-cli):
```
Message("Error(InvalidName(\"DLL.Data storage\"), State { next_error: None, backtrace: None })")
```
 DLL.abi throws InvalidName due to the following snippet from the JSON file:

```json
{
		"constant": true,
		"inputs": [
			{
				"name": "self",
				"type": "DLL.Data storage"
			},
			{
				"name": "_curr",
				"type": "uint256"
			}
		],
		"name": "getNext",
		"outputs": [
			{
				"name": "",
				"type": "uint256"
			}
		],
		"payable": false,
		"stateMutability": "view",
		"type": "function"
	}
```
It seems like it cannot handle "type" being DLL.Data storage. Once changed to a different type such as uint256, error subsides.

[DLL.abi.txt](https://github.com/paritytech/ethabi/files/1644281/DLL.abi.txt)
[DLL.bin.txt](https://github.com/paritytech/ethabi/files/1644282/DLL.bin.txt)
[DLL.sol.txt](https://github.com/paritytech/ethabi/files/1644283/DLL.sol.txt)

**Comment by debris** [comment]
lol, afaik `DLL.Data storage` is an invalid type. I'll report it upstream in the solidity repo

**Comment by akuanti** [comment]
@debris what do you think the compiler should be generating for a type in this situation?

**Comment by debris** [comment]
I don't know. Whatever it used to generate in the past. `DLL.Data storage` is just an arbitrary name and it's impossible to infer anything from it
