### ISSUE TITLE
uint256 encoding problem

### ISSUE THREAD

**Issue by epquick** [paritytech/ethabi#79]
When I am trying to encode big uint256 value I got this error

```
Cannot parse uint256

Caused by:
  number too large to fit in target type
```

I'am trying to do 
```
ethabi encode function abi.json mint -p f3eb3b7d01416d22fdc051c313af5634afac316e -p 10000000000 --lenient
```
or simply
```
ethabi encode params -v uint256 10000000000 --lenient
```
If I trying to encode smaller number like 1000 it works fine (up to 10 ** 9) but starting from 10 ** 10 it raises error. Why? uint256 can store values up to 2 ** 256 - 1 as I understand 

Is it a bug or I am using ethabi incorrectly?

**Comment by axelchalon** [comment]
I opened a PR to fix the encoding error (https://github.com/paritytech/ethabi/pull/80); I still need some help to fix this same issue with i256. In the meantime you can use its branch [fix-lenient-encoding-256](https://github.com/paritytech/ethabi/tree/fix-lenient-encoding-256) :

```
ethabi encode params \
  --lenient \
  -v uint256 1 \
  -v "address[]" "[0097c111bedd43e760be5f8f245c0e5f59d35836]" \
  -v uint256 100000 \
  -v uint256 10000000000000000000

0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000186a00000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000097c111bedd43e760be5f8f245c0e5f59d35836
```

It does take a few seconds to compute though, which is strange behaviour. I have the same behaviour as you upon executing the second command; will have a look into it.

**Comment by dvdplm** [comment]
closed by https://github.com/paritytech/ethabi/pull/173
