### ISSUE TITLE
Verifying the event interface topic

### ISSUE THREAD

**Issue by mbrock** [paritytech/ethabi#8]
Solidity events (non-anonymous) include the Keccak hash of the event signature as part of the first topic.

ethabi doesn't verify that decoded log entries actually match the provided event signature.

As far as I can tell, we only need to verify `signature(name, params) == topics.get(0).unwrap().0[0..4]`.

I've done that in my own program outside ethabi, but it seems to me like ethabi should do this as part of the event decoder.

To avoid a breaking change, we could also expose a separate method for verifying the event interface.

If you agree, I could work on it early next week. If not, my own code is already working, so no worries. :)

**Comment by debris** [comment]
> To avoid a breaking change, we could also expose a separate method for verifying the event interface.

Don't worry about that. Major version can be always updated ;)

**Comment by rphmeier** [comment]
@debris I found I needed this recently as well. Would be a good thing to add in 2.0

**Comment by debris** [comment]
It's already there ;)
