### ISSUE TITLE
docopt argv deserialization takes a very long time

### ISSUE THREAD

**Issue by axelchalon** [paritytech/ethabi#86]
(via https://github.com/paritytech/ethabi/issues/79#issuecomment-368421077)

https://github.com/paritytech/ethabi/blob/master/cli/src/main.rs#L81
`.deserialize()` takes abnormally long to compute; computing time grows exponentially with number of arguments

```
ethabi encode params --lenient -v uint256 1 -v uint256 1 -v uint256 1 -v uint256 1

# hangs a couple seconds on .deserialize()
```

```
ethabi encode params --lenient -v uint256 1 -v uint256 1 -v uint256 1 -v uint256 1 -v uint256 1

# hangs with 100% cpu and a lot of memory usage for at least several minutes (had to kill the process)
```

**Comment by debris** [comment]
I believe this should be reported upstream in docopt repo

**Comment by debris** [comment]
might be related to https://github.com/docopt/docopt.rs/pull/185

**Comment by debris** [comment]
and https://github.com/docopt/docopt.rs/issues/207

**Comment by dvdplm** [comment]
`docopt` has been replaced by `structopt` in `v10` and #164. Closing.
