### ISSUE TITLE
easier and less boilerplatey interaction with contracts using tokio

### ISSUE THREAD

**Issue by snd** [paritytech/ethabi#94]
while working on the bridge i found that using ethabi, web3 and tokio together results in a lot of boilerplate.

the call to fetch a signature for example is a one liner in nodejs (https://github.com/poanetwork/bridge-nodejs/blob/a23ecb78572f3e1928d9129eff8d4118b2618b57/src/processCollectedSignatures.js#L80)
and this in rust
https://github.com/paritytech/parity-bridge/blob/0090447e7768ff2b49cec13dd03a743b55444100/bridge/src/bridge/withdraw_relay.rs#L61,
https://github.com/paritytech/parity-bridge/blob/0090447e7768ff2b49cec13dd03a743b55444100/bridge/src/bridge/withdraw_relay.rs#L86
https://github.com/paritytech/parity-bridge/blob/0090447e7768ff2b49cec13dd03a743b55444100/bridge/src/bridge/withdraw_relay.rs#L184
https://github.com/paritytech/parity-bridge/blob/0090447e7768ff2b49cec13dd03a743b55444100/bridge/src/bridge/withdraw_relay.rs#L235

: /

in rust (with tokio) the input and output part concerned with one call
are far apart as they are separated by the async state machine.

when dealing with lots of calls and transactions this becomes hard to reuse spaghetti...

i started writing higher level wrappers around the auto generated (ethabi) contracts:
https://github.com/paritytech/parity-bridge/blob/snd-refactor/bridge/src/main_contract.rs
https://github.com/paritytech/parity-bridge/blob/snd-refactor/bridge/src/side_contract.rs

now code concerning a specific call is in one place, reusable and the relay code (using it) not cluttered with it:
https://github.com/paritytech/parity-bridge/blob/snd-refactor/bridge/src/main_to_side_sign.rs#L60

now the thought ocurred to me that we could automate (derive) this.

we could start by simply generating futures implementations for each `call` and `transaction`
that present an easy to use API similar to nodejs.

example:

```rust
let future = ForeignBridge::default()
    .functions()
    .has_authority_signed_side_to_main()
    .async(transport, contract_address, authority_address, message_hash);

// no manual calls to input and output
let has_signed: bool = try_ready!(future.poll());
```

(`call` would be nicer but is already taken by ethabi)

**this would make it much easier in general to interact with contracts from rust with tokio.**

@folsen @debris would love to hear your thoughts on this :)

should this be a feature gated part of ethabi (clutters ethabi) or a separate crate (needs access to intermediary data used by ethabi-derive)?

**Comment by folsen** [comment]
Agree the steps and boilerplate you have to deal with in Rust is too much. Your desired example and goals seem great to me, I'm all for it.

I'd rather see it part of ethabi itself, maybe as a separate module that just has this sort of sugar and nicer API using the lower API. But I would defer to @debris opinion on code organisation in general.

**Comment by snd** [comment]
addition:

we could make it possible to initialize a contract struct that holds things like `contract_address` and `transport` so they don't have to be passed to every callsite.

```rust
let foreign = ForeignBridge::new(transport, contract_address);
let future = foreign.has_authority_signed_side_to_main(authority_address, message_hash);

// no manual calls to input and output
let has_signed: bool = try_ready!(future.poll());
```

**Comment by tomusdrw** [comment]
Have you seen https://github.com/paritytech/ethabi/pull/85 ?

The thing you are proposing is pretty much tightly coupling ethabi and web3, with #85 we could do sth like that instead:

```rust
let web3 = Web3::new(transport);
let contract_caller = web3.contract_at(address);

let foreign_bridge = ForeignBridge::default();
let future = foreign_bridge.has_authority_signed_side_to_main(authority_address, message_hash).call(contract_caller);
```

IMHO that gives us a nice clean separation in responsibilities of the library, allows to maintain the old behaviour of ethabi used to just encode and decode calls and opens up option for other client implementations than rust-web3

**Comment by snd** [comment]
totally agree that ethabi should not be coupled to web3. that's not my intention.
solutions that use some trait defined by ethabi that is implemented by web3, etc are much better.

looking into fully understanding #85.

**Comment by snd** [comment]
using the `ContractFunction` trait (which is great!) from #85 alone i will be able to create helpers for the bridge that should already clean this up a lot.

then we can decide whether they are generally useful enough to be moved elsewhere.

something like:

```rust
pub struct AsyncCall<T: Transport, C: ContractFunction> {
    future: CallResult<Bytes, T::Out>,
    function: C,
}

impl<T: Transport, C: ContractFunction> AsyncCall<T, C> {
    pub fn new(transport: T, address: Address, function: C) -> Self {
        let payload = function.encoded();
        let request = CallRequest {
            from: None,
            to: address,
            gas: None,
            gas_price: None,
            value: None,
            data: Some(Bytes(payload)),
        };
        let future = web3::api::Eth::new(transport).call(request, None)
        Self { future, function }
    }
}

impl<T: Transport, C: ContractFunction> Future for AsyncCall<T, C> {
    type Item = C::Output;
    type Error = web3::Error;

    fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
        let response = try_ready!(self.future.poll);
        Ok(Async::Ready(self.function.output(response)?))
    }
}
```

which could be used like:

```rust
let future = AsyncCall::new(
    transport,
    contract_address,
    ForeignBridge::default()
        .functions()
        .has_authority_signed_side_to_main(authority_address, message_hash));

// no manual calls to input and output
let has_signed: bool = try_ready!(future.poll());
```

of course the `transport` and `contract_address` could be moved around inside a single struct (see `contract_caller` above).

**Comment by snd** [comment]
closing this as the situation is sufficiently better now that i'm using the `ContractFunction` trait
