### ISSUE TITLE
*WithInput::Output is () when it should be Address

### ISSUE THREAD

**Issue by snd** [paritytech/ethabi#99]
ran into this while working on sol-rs. also see my comment there https://github.com/paritytech/sol-rs/pull/31#issuecomment-393720739

there's a solidity function that returns an address:
https://github.com/paritytech/sol-rs/blob/2053fe1d805dc2eb5d43abf8de81abe1a401fcb4/tests/contracts/test.sol#L2

ethabi generates to correct return type `Address` for `Outputs`:

![screen shot 2018-06-04 at 5 07 59 pm](https://user-images.githubusercontent.com/32397/40925423-f5a5bbb0-6819-11e8-94df-c8dc06595e60.png)

though for the generated `*WithInput` type the `Output` is `()` **which is incorrect**:

![screen shot 2018-06-04 at 5 07 35 pm](https://user-images.githubusercontent.com/32397/40925490-1ddf2f08-681a-11e8-8407-9c62efb48bc0.png)

@axelchalon would be great if you could have a look since you're more familiar with the code involved. let me know in case you want me to dig in myself

**Comment by axelchalon** [comment]
My understanding is that this is a remnant of when we still used to have `.call()` and `.transact()`, and for non-constant functions `*WithInput::Output` had to match what would be returned by the callback passed to `.transact()` (which, for non-constant functions, was `()` because the return value of the contract function couldn't be known immediately)

**Comment by snd** [comment]
@axelchalon has made a quick fix for this here https://github.com/paritytech/ethabi/tree/ac-fix-output. thanks 👍 

i think `ContractFunction` should be entirely independent from whether it's used in a call or transaction context. that is `ContractFunction::Output` should match the return value of the solidity function regardless of the function modifiers.

**Comment by snd** [comment]
confirming that this is fixed on https://github.com/paritytech/ethabi/tree/ac-fix-output 👍 

@axelchalon want to open a PR?
